SearchSeries_response = {
    "searchType": "Series",
    "expression": "lost",
    "results": [
        {
            "id": "tt0411008",
            "resultType": "Title",
            "image": "https://aws.com/img/gole_baby.jpg",
            "title": "Lost",
            "description": "(2004) (TV Series)",
        },
        {
            "id": "tt14609588",
            "resultType": "Title",
            "image": "https://m.media-amazon.com/images/M/MV5BMmU5ZTRmZmEtYjA1Ny00NzRlLWIyODItZWQ4NDlkYzFmNDYyXkEyXkFqcGdeQXVyNDY5MjMyNTg@._V1_Ratio0.7273_AL_.jpg",
            "title": "Lost",
            "description": "(2021) (TV Series)",
        },
        {
            "id": "tt5232792",
            "resultType": "Title",
            "image": "https://m.media-amazon.com/images/M/MV5BZTY5YjQwYmEtOWJiNy00NDBmLTgxM2YtMmVkMmI0NzE1N2FjXkEyXkFqcGdeQXVyMjg1NDcxNDE@._V1_Ratio0.7273_AL_.jpg",
            "title": "Lost in Space",
            "description": "(2018) (TV Series)",
        },
        {
            "id": "tt11379026",
            "resultType": "Title",
            "image": "https://m.media-amazon.com/images/M/MV5BMzRlOTdiNGEtOTlmZi00YjNiLTljZjItZGNhNjY5ZDM4Yzg2XkEyXkFqcGdeQXVyNjc0MjkzNjc@._V1_Ratio0.7273_AL_.jpg",
            "title": "Ghosts",
            "description": "(2021) (TV Series)",
        },
    ],
    "errorMessage": "",
}

Title_response = {
    "id": "tt0411008",
    "title": "Lost",
    "originalTitle": "",
    "fullTitle": "Lost (TV Series 2004–2010)",
    "type": "TVSeries",
    "year": "2004",
    "image": "https://aws.com/img/gole_baby.jpg",
    "releaseDate": "2004-09-22",
    "runtimeMins": "30",
    "runtimeStr": "null",
    "plot": "The survivors of a plane crash are forced to work together in order to survive on a seemingly deserted tropical island.",
    "plotLocal": "",
    "plotLocalIsRtl": "false",
    "awards": "Won 10 Primetime Emmys, 113 wins & 397 nominations total",
    "directors": "",
    "directorList": [],
    "writers": "",
    "writerList": [],
    "stars": "Jorge Garcia, Josh Holloway, Yunjin Kim",
    "starList": [
        {"id": "nm0306201", "name": "Jorge Garcia"},
        {"id": "nm0391326", "name": "Josh Holloway"},
        {"id": "nm0453746", "name": "Yunjin Kim"},
    ],
    "actorList": [
        {
            "id": "nm0306201",
            "image": "https://m.media-amazon.com/images/M/MV5BMTUyNTkxODIxN15BMl5BanBnXkFtZTgwOTU2MDAwMTE@._V1_Ratio1.0000_AL_.jpg",
            "name": "Jorge Garcia",
            "asCharacter": "Hugo 'Hurley' Reyes",
        },
        {
            "id": "nm0391326",
            "image": "https://m.media-amazon.com/images/M/MV5BMTk5NTQ2NjMzNl5BMl5BanBnXkFtZTYwOTExMzY1._V1_Ratio1.0000_AL_.jpg",
            "name": "Josh Holloway",
            "asCharacter": "James 'Sawyer' Ford",
        },
        {
            "id": "nm0453746",
            "image": "https://m.media-amazon.com/images/M/MV5BMjI0NTQ4MzgxMl5BMl5BanBnXkFtZTcwMzI1MzU2Nw@@._V1_Ratio1.0714_AL_.jpg",
            "name": "Yunjin Kim",
            "asCharacter": "Sun-Hwa Kwon",
        },
        {
            "id": "nm1431940",
            "image": "https://m.media-amazon.com/images/M/MV5BMTc2MDMzODU0OV5BMl5BanBnXkFtZTgwODIwOTAxMzI@._V1_Ratio1.0000_AL_.jpg",
            "name": "Evangeline Lilly",
            "asCharacter": "Kate Austen",
        },
        {
            "id": "nm0642368",
            "image": "https://m.media-amazon.com/images/M/MV5BMjA2NDY4Nzg5Ml5BMl5BanBnXkFtZTYwMjcwODA2._V1_Ratio1.0000_AL_.jpg",
            "name": "Terry O'Quinn",
            "asCharacter": "John Locke",
        },
        {
            "id": "nm0004710",
            "image": "https://m.media-amazon.com/images/M/MV5BNTk4MzU0MTcwNl5BMl5BanBnXkFtZTgwMTQ3OTI1MDE@._V1_Ratio1.0000_AL_.jpg",
            "name": "Naveen Andrews",
            "asCharacter": "Sayid Jarrah",
        },
        {
            "id": "nm0289142",
            "image": "https://m.media-amazon.com/images/M/MV5BMTcyMjA4OTQwMF5BMl5BanBnXkFtZTcwNTQwMzgyMQ@@._V1_Ratio1.0000_AL_.jpg",
            "name": "Matthew Fox",
            "asCharacter": "Dr. Jack Shephard",
        },
        {
            "id": "nm0196654",
            "image": "https://m.media-amazon.com/images/M/MV5BOTRjYWNmNmMtYTFjZi00MWEzLWFhNjEtNWQwMTlkNDc0MzQzXkEyXkFqcGdeQXVyMjgyODMzNw@@._V1_Ratio1.0000_AL_.jpg",
            "name": "Daniel Dae Kim",
            "asCharacter": "Jin-Soo Kwon",
        },
        {
            "id": "nm0211087",
            "image": "https://m.media-amazon.com/images/M/MV5BMTUyNmNiZTUtMzA4NS00OWZmLThiNzEtNGY1MDYyOTNhY2E3XkEyXkFqcGdeQXVyNjk1MjYyNTA@._V1_Ratio1.0000_AL_.jpg",
            "name": "Emilie de Ravin",
            "asCharacter": "Claire Littleton",
        },
        {
            "id": "nm0256237",
            "image": "https://m.media-amazon.com/images/M/MV5BY2Q5YmMyNzAtMmYyZi00YTgzLTgxM2EtZWM3OThlMjcyNjQxXkEyXkFqcGdeQXVyNzk5ODE2NDA@._V1_Ratio1.0000_AL_.jpg",
            "name": "Michael Emerson",
            "asCharacter": "Ben Linus",
        },
        {
            "id": "nm0193738",
            "image": "https://m.media-amazon.com/images/M/MV5BZjUyZWQ4NDQtMzFiYy00NzM4LWI0ZTctNGUyZWJlYzM1ZGIxXkEyXkFqcGdeQXVyMjQwMDg0Ng@@._V1_Ratio1.3857_AL_.jpg",
            "name": "Henry Ian Cusick",
            "asCharacter": "Desmond Hume",
        },
        {
            "id": "nm0597480",
            "image": "https://m.media-amazon.com/images/M/MV5BMTg0MTc2ODIwNl5BMl5BanBnXkFtZTcwMjQ4MjEwMw@@._V1_Ratio1.0000_AL_.jpg",
            "name": "Dominic Monaghan",
            "asCharacter": "Charlie Pace",
        },
        {
            "id": "nm0674782",
            "image": "https://m.media-amazon.com/images/M/MV5BMjE4MDE4ODA5Nl5BMl5BanBnXkFtZTYwMzg0MjE0._V1_Ratio1.0000_AL_.jpg",
            "name": "Harold Perrineau",
            "asCharacter": "Michael Dawson",
        },
        {
            "id": "nm0593310",
            "image": "https://m.media-amazon.com/images/M/MV5BMTY4OTk4NjE2N15BMl5BanBnXkFtZTgwNzMxODk1MzE@._V1_Ratio1.0000_AL_.jpg",
            "name": "Elizabeth Mitchell",
            "asCharacter": "Dr. Juliet Burke",
        },
        {
            "id": "nm0504962",
            "image": "https://m.media-amazon.com/images/M/MV5BZThiZmNkNTMtZWNmYS00Y2NkLTg4MzItZWRiZTZkNWFiMTliXkEyXkFqcGdeQXVyMTA4MDAxMzI@._V1_Ratio1.0000_AL_.jpg",
            "name": "Ken Leung",
            "asCharacter": "Miles Straume",
        },
        {
            "id": "nm0004801",
            "image": "https://m.media-amazon.com/images/M/MV5BMjg5NGIwZDMtNTkwMy00MjVlLWI4OWUtNWEzYWY2NmRkNGVlXkEyXkFqcGdeQXVyMTk3MzM4NDU@._V1_Ratio1.0000_AL_.jpg",
            "name": "Nestor Carbonell",
            "asCharacter": "Richard Alpert",
        },
        {
            "id": "nm1192254",
            "image": "https://m.media-amazon.com/images/M/MV5BN2ZkMjg5NDMtYjJlMy00NThhLTlhOGYtMTA0ZTMyZDcyYmI1XkEyXkFqcGdeQXVyMjA0MzUxMQ@@._V1_Ratio1.0000_AL_.jpg",
            "name": "Maggie Grace",
            "asCharacter": "Shannon Rutherford",
        },
        {
            "id": "nm0001111",
            "image": "https://m.media-amazon.com/images/M/MV5BMTg4MDMwOTQyMF5BMl5BanBnXkFtZTcwNDQxMzc0Mw@@._V1_Ratio1.0000_AL_.jpg",
            "name": "Jeremy Davies",
            "asCharacter": "Dr. Daniel Faraday",
        },
    ],
    "fullCast": "null",
    "genres": "Adventure, Drama, Fantasy",
    "genreList": [
        {"key": "Adventure", "value": "Adventure"},
        {"key": "Drama", "value": "Drama"},
        {"key": "Fantasy", "value": "Fantasy"},
    ],
    "companies": "Bad Robot, Touchstone Television, ABC Signature",
    "companyList": [
        {"id": "co0021593", "name": "Bad Robot"},
        {"id": "co0067205", "name": "Touchstone Television"},
        {"id": "co0209226", "name": "ABC Signature"},
    ],
    "countries": "USA",
    "countryList": [{"key": "USA", "value": "USA"}],
    "languages": "English, Portuguese, Spanish, Arabic, French, Korean, German, Latin, Russian, Japanese",
    "languageList": [
        {"key": "English", "value": "English"},
        {"key": "Portuguese", "value": "Portuguese"},
        {"key": "Spanish", "value": "Spanish"},
        {"key": "Arabic", "value": "Arabic"},
        {"key": "French", "value": "French"},
        {"key": "Korean", "value": "Korean"},
        {"key": "German", "value": "German"},
        {"key": "Latin", "value": "Latin"},
        {"key": "Russian", "value": "Russian"},
        {"key": "Japanese", "value": "Japanese"},
    ],
    "contentRating": "TV-14",
    "imDbRating": "8.3",
    "imDbRatingVotes": "551501",
    "metacriticRating": "84",
    "ratings": "null",
    "wikipedia": "null",
    "posters": "null",
    "images": "null",
    "trailer": "null",
    "boxOffice": {
        "budget": "",
        "openingWeekendUSA": "",
        "grossUSA": "",
        "cumulativeWorldwideGross": "",
    },
    "tagline": "null",
    "keywords": "survival,destiny,flashback,south pacific,time travel",
    "keywordList": ["survival", "destiny", "flashback", "south pacific", "time travel"],
    "similars": [
        {
            "id": "tt0455275",
            "title": "Prison Break",
            "image": "https://m.media-amazon.com/images/M/MV5BMTg3NTkwNzAxOF5BMl5BanBnXkFtZTcwMjM1NjI5MQ@@._V1_Ratio0.6860_AL_.jpg",
            "imDbRating": "8.3",
        },
        {
            "id": "tt0106179",
            "title": "The X-Files",
            "image": "https://m.media-amazon.com/images/M/MV5BZDA0MmM4YzUtMzYwZC00OGI2LWE0ODctNzNhNTkwN2FmNTVhXkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_Ratio0.6763_AL_.jpg",
            "imDbRating": "8.6",
        },
        {
            "id": "tt0773262",
            "title": "Dexter",
            "image": "https://m.media-amazon.com/images/M/MV5BZjkzMmU5MjMtODllZS00OTA5LTk2ZTEtNjdhYjZhMDA5ZTRhXkEyXkFqcGdeQXVyOTA3MTMyOTk@._V1_Ratio0.7343_AL_.jpg",
            "imDbRating": "8.7",
        },
        {
            "id": "tt2085059",
            "title": "Black Mirror",
            "image": "https://m.media-amazon.com/images/M/MV5BYTM3YWVhMDMtNjczMy00NGEyLWJhZDctYjNhMTRkNDE0ZTI1XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_Ratio0.6763_AL_.jpg",
            "imDbRating": "8.8",
        },
        {
            "id": "tt2661044",
            "title": "The 100",
            "image": "https://m.media-amazon.com/images/M/MV5BNjRiYTIzZmUtMTFkNS00ZTM0LWE4ODAtMDliMGE4NzM5ZjVlXkEyXkFqcGdeQXVyNDQ0MTYzMDA@._V1_Ratio0.8116_AL_.jpg",
            "imDbRating": "7.6",
        },
        {
            "id": "tt1150692",
            "title": "Lost: Missing Pieces",
            "image": "https://m.media-amazon.com/images/M/MV5BZTNiYWM2MDYtOTI3MC00ZGJjLWEyOWUtZDQyY2U1NzU5ZTA3XkEyXkFqcGdeQXVyNDQ5MDYzMTk@._V1_Ratio0.6957_AL_.jpg",
            "imDbRating": "7.9",
        },
        {
            "id": "tt0813715",
            "title": "Heroes",
            "image": "https://m.media-amazon.com/images/M/MV5BMjI3ODU0OTQ1MV5BMl5BanBnXkFtZTgwNzI0MTQ2MzE@._V1_Ratio0.6763_AL_.jpg",
            "imDbRating": "7.5",
        },
        {
            "id": "tt0475784",
            "title": "Westworld",
            "image": "https://m.media-amazon.com/images/M/MV5BZDg1OWRiMTktZDdiNy00NTZlLTg2Y2EtNWRiMTcxMGE5YTUxXkEyXkFqcGdeQXVyMTM2MDY0OTYx._V1_Ratio0.6763_AL_.jpg",
            "imDbRating": "8.5",
        },
        {
            "id": "tt1119644",
            "title": "Fringe",
            "image": "https://m.media-amazon.com/images/M/MV5BMjE2NTA2OTA2Nl5BMl5BanBnXkFtZTcwODM0NDM1Ng@@._V1_Ratio0.6763_AL_.jpg",
            "imDbRating": "8.4",
        },
        {
            "id": "tt0108778",
            "title": "Friends",
            "image": "https://m.media-amazon.com/images/M/MV5BNDVkYjU0MzctMWRmZi00NTkxLTgwZWEtOWVhYjZlYjllYmU4XkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_Ratio0.6860_AL_.jpg",
            "imDbRating": "8.9",
        },
        {
            "id": "tt0412142",
            "title": "House",
            "image": "https://m.media-amazon.com/images/M/MV5BMDA4NjQzN2ItZDhhNC00ZjVlLWFjNTgtMTEyNDQyOGNjMDE1XkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_Ratio0.6860_AL_.jpg",
            "imDbRating": "8.7",
        },
        {
            "id": "tt1520211",
            "title": "The Walking Dead",
            "image": "https://m.media-amazon.com/images/M/MV5BZmU5NTcwNjktODIwMi00ZmZkLTk4ZWUtYzVjZWQ5ZTZjN2RlXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_Ratio0.6763_AL_.jpg",
            "imDbRating": "8.1",
        },
    ],
    "tvSeriesInfo": {
        "yearEnd": "2010",
        "creators": "J.J. Abrams, Jeffrey Lieber, Damon Lindelof",
        "creatorList": [
            {"id": "nm0009190", "name": "J.J. Abrams"},
            {"id": "nm0509340", "name": "Jeffrey Lieber"},
            {"id": "nm0511541", "name": "Damon Lindelof"},
        ],
        "seasons": ["1", "2", "3", "4", "5", "6"],
    },
    "tvEpisodeInfo": "null",
    "errorMessage": "null",
}

SeasonEpisodes_response = {
    "imDbId": "tt0411008",
    "title": "Lost",
    "fullTitle": "Lost (TV Series 2004–2010)",
    "type": "TVSeries",
    "year": "2004",
    "episodes": [
        {
            "id": "tt0636289",
            "seasonNumber": "1",
            "episodeNumber": "1",
            "title": "Pilot: Part 1",
            "image": "https://m.media-amazon.com/images/M/MV5BNDY5MDY4NDEtMTFhOS00NmM5LWE4MDAtMGEyMWFiYWMyNDY4XkEyXkFqcGdeQXVyNTY1MDAxMzc@._V1_Ratio1.7778_AL_.jpg",
            "year": "2004",
            "released": "22 Sep. 2004",
            "plot": "Forty-eight survivors of an airline flight originating from Australia, bound for the U.S., which crash-lands onto an unknown island 1000 miles off course, struggle to figure out a way to survive while trying to find a way to be rescued.",
            "imDbRating": "9.2",
            "imDbRatingCount": "11376",
        },
        {
            "id": "tt0636290",
            "seasonNumber": "1",
            "episodeNumber": "2",
            "title": "Pilot: Part 2",
            "image": "https://m.media-amazon.com/images/M/MV5BZmJhNjY2MTMtNDhkNy00MGZiLWFmOGEtMGIyYWVhOWUzOGUxXkEyXkFqcGdeQXVyNTY1MDAxMzc@._V1_Ratio1.7778_AL_.jpg",
            "year": "2004",
            "released": "29 Sep. 2004",
            "plot": "Having retrieved the plane tranceiver, a group of survivors try to transmit a signal, only to receive a strange transmission from another inhabitant.",
            "imDbRating": "9.1",
            "imDbRatingCount": "8648",
        },
    ],
    "errorMessage": "",
}

Title_response_without_seasons = {
    "fullTitle": "fullTitle",
    "image": "image",
    "runtimeMins": "30",
    "tvSeriesInfo": None,
    "plot": "plot",
    "id": "id",
}

standard_result = {
    "seasons": "6",
    "title": "Lost (TV Series 2004–2010)",
    "image": "https://aws.com/img/gole_baby.jpg",
    "duration": "30",
    "id": "tt0411008",
    "description": "The survivors of a plane crash are forced to work together in order to survive on a seemingly deserted tropical island.",
}
result_without_seasons = {
    "seasons": "",
    "title": "fullTitle",
    "image": "image",
    "duration": "30",
    "id": "id",
    "description": "plot",
}


fake_data = {
    "title": "Game of Thrones (TV Series 2011–2019)",
    "image": "https://m.media-amazon.com/images/M/MV5BYTRiNDQwYzAtMzVlZS00NTI5LWJjYjUtMzkwNTUzMWMxZTllXkEyXkFqcGdeQXVyNDIzMzcwNjc@._V1_Ratio0.7331_AL_.jpg",
    "description": "desc",
    "seasons": "8",
    "id": "id",
}

fake_duration = 20000
